package model.dao;
// Generated 07/09/2016 21:42:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer clienteCodigo;
     private String clienteCnpjcpf;
     private String clienteNome;
     private String clienteEmail;
     private Set telefoneClientes = new HashSet(0);
     private Set vendas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String clienteCnpjcpf, String clienteNome) {
        this.clienteCnpjcpf = clienteCnpjcpf;
        this.clienteNome = clienteNome;
    }
    public Cliente(String clienteCnpjcpf, String clienteNome, String clienteEmail, Set telefoneClientes, Set vendas) {
       this.clienteCnpjcpf = clienteCnpjcpf;
       this.clienteNome = clienteNome;
       this.clienteEmail = clienteEmail;
       this.telefoneClientes = telefoneClientes;
       this.vendas = vendas;
    }
   
    public Integer getClienteCodigo() {
        return this.clienteCodigo;
    }
    
    public void setClienteCodigo(Integer clienteCodigo) {
        this.clienteCodigo = clienteCodigo;
    }
    public String getClienteCnpjcpf() {
        return this.clienteCnpjcpf;
    }
    
    public void setClienteCnpjcpf(String clienteCnpjcpf) {
        this.clienteCnpjcpf = clienteCnpjcpf;
    }
    public String getClienteNome() {
        return this.clienteNome;
    }
    
    public void setClienteNome(String clienteNome) {
        this.clienteNome = clienteNome;
    }
    public String getClienteEmail() {
        return this.clienteEmail;
    }
    
    public void setClienteEmail(String clienteEmail) {
        this.clienteEmail = clienteEmail;
    }
    public Set getTelefoneClientes() {
        return this.telefoneClientes;
    }
    
    public void setTelefoneClientes(Set telefoneClientes) {
        this.telefoneClientes = telefoneClientes;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


