package model.dao;
// Generated 07/09/2016 21:42:17 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * FornecedorHasRacao generated by hbm2java
 */
public class FornecedorHasRacao  implements java.io.Serializable {


     private Integer fornecedorHasRacaoCodigo;
     private Fornecedor fornecedor;
     private Racao racao;
     private int fornecedorHasRacaoNumeroNf;
     private BigDecimal fornecedorHasRacaoQtdRacao;
     private String fornecedorHasRacaoUnidDeMedida;

    public FornecedorHasRacao() {
    }

    public FornecedorHasRacao(Fornecedor fornecedor, Racao racao, int fornecedorHasRacaoNumeroNf, BigDecimal fornecedorHasRacaoQtdRacao, String fornecedorHasRacaoUnidDeMedida) {
       this.fornecedor = fornecedor;
       this.racao = racao;
       this.fornecedorHasRacaoNumeroNf = fornecedorHasRacaoNumeroNf;
       this.fornecedorHasRacaoQtdRacao = fornecedorHasRacaoQtdRacao;
       this.fornecedorHasRacaoUnidDeMedida = fornecedorHasRacaoUnidDeMedida;
    }
   
    public Integer getFornecedorHasRacaoCodigo() {
        return this.fornecedorHasRacaoCodigo;
    }
    
    public void setFornecedorHasRacaoCodigo(Integer fornecedorHasRacaoCodigo) {
        this.fornecedorHasRacaoCodigo = fornecedorHasRacaoCodigo;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public Racao getRacao() {
        return this.racao;
    }
    
    public void setRacao(Racao racao) {
        this.racao = racao;
    }
    public int getFornecedorHasRacaoNumeroNf() {
        return this.fornecedorHasRacaoNumeroNf;
    }
    
    public void setFornecedorHasRacaoNumeroNf(int fornecedorHasRacaoNumeroNf) {
        this.fornecedorHasRacaoNumeroNf = fornecedorHasRacaoNumeroNf;
    }
    public BigDecimal getFornecedorHasRacaoQtdRacao() {
        return this.fornecedorHasRacaoQtdRacao;
    }
    
    public void setFornecedorHasRacaoQtdRacao(BigDecimal fornecedorHasRacaoQtdRacao) {
        this.fornecedorHasRacaoQtdRacao = fornecedorHasRacaoQtdRacao;
    }
    public String getFornecedorHasRacaoUnidDeMedida() {
        return this.fornecedorHasRacaoUnidDeMedida;
    }
    
    public void setFornecedorHasRacaoUnidDeMedida(String fornecedorHasRacaoUnidDeMedida) {
        this.fornecedorHasRacaoUnidDeMedida = fornecedorHasRacaoUnidDeMedida;
    }




}


