package model.dao;
// Generated 07/09/2016 21:42:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private Integer fornecedorCodigo;
     private String fornecedorNome;
     private String fornecedorCnpj;
     private String fornecedorEmail;
     private String fornecedorComentarios;
     private String fornecedorEndCep;
     private String fornecedorEndBairro;
     private String fornecedorEndRua;
     private String fornecedorEndNumero;
     private Set telefoneFornecedors = new HashSet(0);
     private Set fornecedorHasRacaos = new HashSet(0);

    public Fornecedor() {
    }

	
    public Fornecedor(String fornecedorNome, String fornecedorCnpj, String fornecedorEmail, String fornecedorComentarios) {
        this.fornecedorNome = fornecedorNome;
        this.fornecedorCnpj = fornecedorCnpj;
        this.fornecedorEmail = fornecedorEmail;
        this.fornecedorComentarios = fornecedorComentarios;
    }
    public Fornecedor(String fornecedorNome, String fornecedorCnpj, String fornecedorEmail, String fornecedorComentarios, String fornecedorEndCep, String fornecedorEndBairro, String fornecedorEndRua, String fornecedorEndNumero, Set telefoneFornecedors, Set fornecedorHasRacaos) {
       this.fornecedorNome = fornecedorNome;
       this.fornecedorCnpj = fornecedorCnpj;
       this.fornecedorEmail = fornecedorEmail;
       this.fornecedorComentarios = fornecedorComentarios;
       this.fornecedorEndCep = fornecedorEndCep;
       this.fornecedorEndBairro = fornecedorEndBairro;
       this.fornecedorEndRua = fornecedorEndRua;
       this.fornecedorEndNumero = fornecedorEndNumero;
       this.telefoneFornecedors = telefoneFornecedors;
       this.fornecedorHasRacaos = fornecedorHasRacaos;
    }
   
    public Integer getFornecedorCodigo() {
        return this.fornecedorCodigo;
    }
    
    public void setFornecedorCodigo(Integer fornecedorCodigo) {
        this.fornecedorCodigo = fornecedorCodigo;
    }
    public String getFornecedorNome() {
        return this.fornecedorNome;
    }
    
    public void setFornecedorNome(String fornecedorNome) {
        this.fornecedorNome = fornecedorNome;
    }
    public String getFornecedorCnpj() {
        return this.fornecedorCnpj;
    }
    
    public void setFornecedorCnpj(String fornecedorCnpj) {
        this.fornecedorCnpj = fornecedorCnpj;
    }
    public String getFornecedorEmail() {
        return this.fornecedorEmail;
    }
    
    public void setFornecedorEmail(String fornecedorEmail) {
        this.fornecedorEmail = fornecedorEmail;
    }
    public String getFornecedorComentarios() {
        return this.fornecedorComentarios;
    }
    
    public void setFornecedorComentarios(String fornecedorComentarios) {
        this.fornecedorComentarios = fornecedorComentarios;
    }
    public String getFornecedorEndCep() {
        return this.fornecedorEndCep;
    }
    
    public void setFornecedorEndCep(String fornecedorEndCep) {
        this.fornecedorEndCep = fornecedorEndCep;
    }
    public String getFornecedorEndBairro() {
        return this.fornecedorEndBairro;
    }
    
    public void setFornecedorEndBairro(String fornecedorEndBairro) {
        this.fornecedorEndBairro = fornecedorEndBairro;
    }
    public String getFornecedorEndRua() {
        return this.fornecedorEndRua;
    }
    
    public void setFornecedorEndRua(String fornecedorEndRua) {
        this.fornecedorEndRua = fornecedorEndRua;
    }
    public String getFornecedorEndNumero() {
        return this.fornecedorEndNumero;
    }
    
    public void setFornecedorEndNumero(String fornecedorEndNumero) {
        this.fornecedorEndNumero = fornecedorEndNumero;
    }
    public Set getTelefoneFornecedors() {
        return this.telefoneFornecedors;
    }
    
    public void setTelefoneFornecedors(Set telefoneFornecedors) {
        this.telefoneFornecedors = telefoneFornecedors;
    }
    public Set getFornecedorHasRacaos() {
        return this.fornecedorHasRacaos;
    }
    
    public void setFornecedorHasRacaos(Set fornecedorHasRacaos) {
        this.fornecedorHasRacaos = fornecedorHasRacaos;
    }




}


