package model.dao;
// Generated 07/09/2016 21:42:17 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Gaiola generated by hbm2java
 */
public class Gaiola  implements java.io.Serializable {


     private Integer gaiolaCodigo;
     private StatusGaiola statusGaiola;
     private TipoEstrutura tipoEstrutura;
     private BigDecimal gaiolaTamTotalM3;
     private BigDecimal gaiolaTamAltura;
     private BigDecimal gaiolaTamComprimento;
     private BigDecimal gaiolaTamLargura;
     private Date gaiolaDataCricao;
     private Set registraLotedepeixes = new HashSet(0);
     private Set alimentas = new HashSet(0);

    public Gaiola() {
    }

	
    public Gaiola(StatusGaiola statusGaiola, TipoEstrutura tipoEstrutura, BigDecimal gaiolaTamTotalM3, BigDecimal gaiolaTamAltura, BigDecimal gaiolaTamComprimento, BigDecimal gaiolaTamLargura, Date gaiolaDataCricao) {
        this.statusGaiola = statusGaiola;
        this.tipoEstrutura = tipoEstrutura;
        this.gaiolaTamTotalM3 = gaiolaTamTotalM3;
        this.gaiolaTamAltura = gaiolaTamAltura;
        this.gaiolaTamComprimento = gaiolaTamComprimento;
        this.gaiolaTamLargura = gaiolaTamLargura;
        this.gaiolaDataCricao = gaiolaDataCricao;
    }
    public Gaiola(StatusGaiola statusGaiola, TipoEstrutura tipoEstrutura, BigDecimal gaiolaTamTotalM3, BigDecimal gaiolaTamAltura, BigDecimal gaiolaTamComprimento, BigDecimal gaiolaTamLargura, Date gaiolaDataCricao, Set registraLotedepeixes, Set alimentas) {
       this.statusGaiola = statusGaiola;
       this.tipoEstrutura = tipoEstrutura;
       this.gaiolaTamTotalM3 = gaiolaTamTotalM3;
       this.gaiolaTamAltura = gaiolaTamAltura;
       this.gaiolaTamComprimento = gaiolaTamComprimento;
       this.gaiolaTamLargura = gaiolaTamLargura;
       this.gaiolaDataCricao = gaiolaDataCricao;
       this.registraLotedepeixes = registraLotedepeixes;
       this.alimentas = alimentas;
    }
   
    public Integer getGaiolaCodigo() {
        return this.gaiolaCodigo;
    }
    
    public void setGaiolaCodigo(Integer gaiolaCodigo) {
        this.gaiolaCodigo = gaiolaCodigo;
    }
    public StatusGaiola getStatusGaiola() {
        return this.statusGaiola;
    }
    
    public void setStatusGaiola(StatusGaiola statusGaiola) {
        this.statusGaiola = statusGaiola;
    }
    public TipoEstrutura getTipoEstrutura() {
        return this.tipoEstrutura;
    }
    
    public void setTipoEstrutura(TipoEstrutura tipoEstrutura) {
        this.tipoEstrutura = tipoEstrutura;
    }
    public BigDecimal getGaiolaTamTotalM3() {
        return this.gaiolaTamTotalM3;
    }
    
    public void setGaiolaTamTotalM3(BigDecimal gaiolaTamTotalM3) {
        this.gaiolaTamTotalM3 = gaiolaTamTotalM3;
    }
    public BigDecimal getGaiolaTamAltura() {
        return this.gaiolaTamAltura;
    }
    
    public void setGaiolaTamAltura(BigDecimal gaiolaTamAltura) {
        this.gaiolaTamAltura = gaiolaTamAltura;
    }
    public BigDecimal getGaiolaTamComprimento() {
        return this.gaiolaTamComprimento;
    }
    
    public void setGaiolaTamComprimento(BigDecimal gaiolaTamComprimento) {
        this.gaiolaTamComprimento = gaiolaTamComprimento;
    }
    public BigDecimal getGaiolaTamLargura() {
        return this.gaiolaTamLargura;
    }
    
    public void setGaiolaTamLargura(BigDecimal gaiolaTamLargura) {
        this.gaiolaTamLargura = gaiolaTamLargura;
    }
    public Date getGaiolaDataCricao() {
        return this.gaiolaDataCricao;
    }
    
    public void setGaiolaDataCricao(Date gaiolaDataCricao) {
        this.gaiolaDataCricao = gaiolaDataCricao;
    }
    public Set getRegistraLotedepeixes() {
        return this.registraLotedepeixes;
    }
    
    public void setRegistraLotedepeixes(Set registraLotedepeixes) {
        this.registraLotedepeixes = registraLotedepeixes;
    }
    public Set getAlimentas() {
        return this.alimentas;
    }
    
    public void setAlimentas(Set alimentas) {
        this.alimentas = alimentas;
    }




}


