package model.dao;
// Generated 07/09/2016 21:42:17 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Racao generated by hbm2java
 */
public class Racao  implements java.io.Serializable {


     private Integer racaoCodigo;
     private String racaoNome;
     private BigDecimal racaoEstoque;
     private BigDecimal racaoPreco;
     private Set fornecedorHasRacaos = new HashSet(0);
     private Set alimentas = new HashSet(0);

    public Racao() {
    }

	
    public Racao(String racaoNome, BigDecimal racaoEstoque, BigDecimal racaoPreco) {
        this.racaoNome = racaoNome;
        this.racaoEstoque = racaoEstoque;
        this.racaoPreco = racaoPreco;
    }
    public Racao(String racaoNome, BigDecimal racaoEstoque, BigDecimal racaoPreco, Set fornecedorHasRacaos, Set alimentas) {
       this.racaoNome = racaoNome;
       this.racaoEstoque = racaoEstoque;
       this.racaoPreco = racaoPreco;
       this.fornecedorHasRacaos = fornecedorHasRacaos;
       this.alimentas = alimentas;
    }
   
    public Integer getRacaoCodigo() {
        return this.racaoCodigo;
    }
    
    public void setRacaoCodigo(Integer racaoCodigo) {
        this.racaoCodigo = racaoCodigo;
    }
    public String getRacaoNome() {
        return this.racaoNome;
    }
    
    public void setRacaoNome(String racaoNome) {
        this.racaoNome = racaoNome;
    }
    public BigDecimal getRacaoEstoque() {
        return this.racaoEstoque;
    }
    
    public void setRacaoEstoque(BigDecimal racaoEstoque) {
        this.racaoEstoque = racaoEstoque;
    }
    public BigDecimal getRacaoPreco() {
        return this.racaoPreco;
    }
    
    public void setRacaoPreco(BigDecimal racaoPreco) {
        this.racaoPreco = racaoPreco;
    }
    public Set getFornecedorHasRacaos() {
        return this.fornecedorHasRacaos;
    }
    
    public void setFornecedorHasRacaos(Set fornecedorHasRacaos) {
        this.fornecedorHasRacaos = fornecedorHasRacaos;
    }
    public Set getAlimentas() {
        return this.alimentas;
    }
    
    public void setAlimentas(Set alimentas) {
        this.alimentas = alimentas;
    }




}


