package model.dao;
// Generated 07/09/2016 21:42:17 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Realiza generated by hbm2java
 */
public class Realiza  implements java.io.Serializable {


     private Integer realizaCodigo;
     private Biometria biometria;
     private Funcionario funcionario;
     private RegistraLotedepeixe registraLotedepeixe;
     private BigDecimal realizaPeso;
     private BigDecimal realizaTamanho;

    public Realiza() {
    }

    public Realiza(Biometria biometria, Funcionario funcionario, RegistraLotedepeixe registraLotedepeixe, BigDecimal realizaPeso, BigDecimal realizaTamanho) {
       this.biometria = biometria;
       this.funcionario = funcionario;
       this.registraLotedepeixe = registraLotedepeixe;
       this.realizaPeso = realizaPeso;
       this.realizaTamanho = realizaTamanho;
    }
   
    public Integer getRealizaCodigo() {
        return this.realizaCodigo;
    }
    
    public void setRealizaCodigo(Integer realizaCodigo) {
        this.realizaCodigo = realizaCodigo;
    }
    public Biometria getBiometria() {
        return this.biometria;
    }
    
    public void setBiometria(Biometria biometria) {
        this.biometria = biometria;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public RegistraLotedepeixe getRegistraLotedepeixe() {
        return this.registraLotedepeixe;
    }
    
    public void setRegistraLotedepeixe(RegistraLotedepeixe registraLotedepeixe) {
        this.registraLotedepeixe = registraLotedepeixe;
    }
    public BigDecimal getRealizaPeso() {
        return this.realizaPeso;
    }
    
    public void setRealizaPeso(BigDecimal realizaPeso) {
        this.realizaPeso = realizaPeso;
    }
    public BigDecimal getRealizaTamanho() {
        return this.realizaTamanho;
    }
    
    public void setRealizaTamanho(BigDecimal realizaTamanho) {
        this.realizaTamanho = realizaTamanho;
    }




}


