package model.dao;
// Generated 07/09/2016 21:42:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * StatusGaiola generated by hbm2java
 */
public class StatusGaiola  implements java.io.Serializable {


     private Integer statusGaiolaCodigo;
     private String statusGaiolaDescricao;
     private Set gaiolas = new HashSet(0);

    public StatusGaiola() {
    }

	
    public StatusGaiola(String statusGaiolaDescricao) {
        this.statusGaiolaDescricao = statusGaiolaDescricao;
    }
    public StatusGaiola(String statusGaiolaDescricao, Set gaiolas) {
       this.statusGaiolaDescricao = statusGaiolaDescricao;
       this.gaiolas = gaiolas;
    }
   
    public Integer getStatusGaiolaCodigo() {
        return this.statusGaiolaCodigo;
    }
    
    public void setStatusGaiolaCodigo(Integer statusGaiolaCodigo) {
        this.statusGaiolaCodigo = statusGaiolaCodigo;
    }
    public String getStatusGaiolaDescricao() {
        return this.statusGaiolaDescricao;
    }
    
    public void setStatusGaiolaDescricao(String statusGaiolaDescricao) {
        this.statusGaiolaDescricao = statusGaiolaDescricao;
    }
    public Set getGaiolas() {
        return this.gaiolas;
    }
    
    public void setGaiolas(Set gaiolas) {
        this.gaiolas = gaiolas;
    }




}


