package model.dao;
// Generated 07/09/2016 21:42:17 by Hibernate Tools 4.3.1



/**
 * TelefoneFornecedor generated by hbm2java
 */
public class TelefoneFornecedor  implements java.io.Serializable {


     private Integer telefoneFornecedorCodigo;
     private Fornecedor fornecedor;
     private String telefoneFornecedorPrefixoFixo;
     private String telefoneFornecedorFixo;
     private String telefoneFornecedorPrefixoCelular;
     private String telefoneFornecedorCelular;

    public TelefoneFornecedor() {
    }

    public TelefoneFornecedor(Fornecedor fornecedor, String telefoneFornecedorPrefixoFixo, String telefoneFornecedorFixo, String telefoneFornecedorPrefixoCelular, String telefoneFornecedorCelular) {
       this.fornecedor = fornecedor;
       this.telefoneFornecedorPrefixoFixo = telefoneFornecedorPrefixoFixo;
       this.telefoneFornecedorFixo = telefoneFornecedorFixo;
       this.telefoneFornecedorPrefixoCelular = telefoneFornecedorPrefixoCelular;
       this.telefoneFornecedorCelular = telefoneFornecedorCelular;
    }
   
    public Integer getTelefoneFornecedorCodigo() {
        return this.telefoneFornecedorCodigo;
    }
    
    public void setTelefoneFornecedorCodigo(Integer telefoneFornecedorCodigo) {
        this.telefoneFornecedorCodigo = telefoneFornecedorCodigo;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public String getTelefoneFornecedorPrefixoFixo() {
        return this.telefoneFornecedorPrefixoFixo;
    }
    
    public void setTelefoneFornecedorPrefixoFixo(String telefoneFornecedorPrefixoFixo) {
        this.telefoneFornecedorPrefixoFixo = telefoneFornecedorPrefixoFixo;
    }
    public String getTelefoneFornecedorFixo() {
        return this.telefoneFornecedorFixo;
    }
    
    public void setTelefoneFornecedorFixo(String telefoneFornecedorFixo) {
        this.telefoneFornecedorFixo = telefoneFornecedorFixo;
    }
    public String getTelefoneFornecedorPrefixoCelular() {
        return this.telefoneFornecedorPrefixoCelular;
    }
    
    public void setTelefoneFornecedorPrefixoCelular(String telefoneFornecedorPrefixoCelular) {
        this.telefoneFornecedorPrefixoCelular = telefoneFornecedorPrefixoCelular;
    }
    public String getTelefoneFornecedorCelular() {
        return this.telefoneFornecedorCelular;
    }
    
    public void setTelefoneFornecedorCelular(String telefoneFornecedorCelular) {
        this.telefoneFornecedorCelular = telefoneFornecedorCelular;
    }




}


