package model.dao;
// Generated 07/09/2016 21:42:17 by Hibernate Tools 4.3.1



/**
 * TelefoneCliente generated by hbm2java
 */
public class TelefoneCliente  implements java.io.Serializable {


     private Integer telefoneClienteCodigo;
     private Cliente cliente;
     private String telefoneClientePrefixoFixo;
     private String telefoneClienteFixo;
     private String telefoneClientePrefixoCelular;
     private String telefoneClienteCelular;

    public TelefoneCliente() {
    }

	
    public TelefoneCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public TelefoneCliente(Cliente cliente, String telefoneClientePrefixoFixo, String telefoneClienteFixo, String telefoneClientePrefixoCelular, String telefoneClienteCelular) {
       this.cliente = cliente;
       this.telefoneClientePrefixoFixo = telefoneClientePrefixoFixo;
       this.telefoneClienteFixo = telefoneClienteFixo;
       this.telefoneClientePrefixoCelular = telefoneClientePrefixoCelular;
       this.telefoneClienteCelular = telefoneClienteCelular;
    }
   
    public Integer getTelefoneClienteCodigo() {
        return this.telefoneClienteCodigo;
    }
    
    public void setTelefoneClienteCodigo(Integer telefoneClienteCodigo) {
        this.telefoneClienteCodigo = telefoneClienteCodigo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getTelefoneClientePrefixoFixo() {
        return this.telefoneClientePrefixoFixo;
    }
    
    public void setTelefoneClientePrefixoFixo(String telefoneClientePrefixoFixo) {
        this.telefoneClientePrefixoFixo = telefoneClientePrefixoFixo;
    }
    public String getTelefoneClienteFixo() {
        return this.telefoneClienteFixo;
    }
    
    public void setTelefoneClienteFixo(String telefoneClienteFixo) {
        this.telefoneClienteFixo = telefoneClienteFixo;
    }
    public String getTelefoneClientePrefixoCelular() {
        return this.telefoneClientePrefixoCelular;
    }
    
    public void setTelefoneClientePrefixoCelular(String telefoneClientePrefixoCelular) {
        this.telefoneClientePrefixoCelular = telefoneClientePrefixoCelular;
    }
    public String getTelefoneClienteCelular() {
        return this.telefoneClienteCelular;
    }
    
    public void setTelefoneClienteCelular(String telefoneClienteCelular) {
        this.telefoneClienteCelular = telefoneClienteCelular;
    }




}


