package model.dao;
// Generated 07/09/2016 21:42:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoEstrutura generated by hbm2java
 */
public class TipoEstrutura  implements java.io.Serializable {


     private Integer tipoEstruturaCodigo;
     private int tipoEstruturaPrazoDeVidaMeses;
     private String tipoEstruturaDescricao;
     private Set gaiolas = new HashSet(0);

    public TipoEstrutura() {
    }

	
    public TipoEstrutura(int tipoEstruturaPrazoDeVidaMeses, String tipoEstruturaDescricao) {
        this.tipoEstruturaPrazoDeVidaMeses = tipoEstruturaPrazoDeVidaMeses;
        this.tipoEstruturaDescricao = tipoEstruturaDescricao;
    }
    public TipoEstrutura(int tipoEstruturaPrazoDeVidaMeses, String tipoEstruturaDescricao, Set gaiolas) {
       this.tipoEstruturaPrazoDeVidaMeses = tipoEstruturaPrazoDeVidaMeses;
       this.tipoEstruturaDescricao = tipoEstruturaDescricao;
       this.gaiolas = gaiolas;
    }
   
    public Integer getTipoEstruturaCodigo() {
        return this.tipoEstruturaCodigo;
    }
    
    public void setTipoEstruturaCodigo(Integer tipoEstruturaCodigo) {
        this.tipoEstruturaCodigo = tipoEstruturaCodigo;
    }
    public int getTipoEstruturaPrazoDeVidaMeses() {
        return this.tipoEstruturaPrazoDeVidaMeses;
    }
    
    public void setTipoEstruturaPrazoDeVidaMeses(int tipoEstruturaPrazoDeVidaMeses) {
        this.tipoEstruturaPrazoDeVidaMeses = tipoEstruturaPrazoDeVidaMeses;
    }
    public String getTipoEstruturaDescricao() {
        return this.tipoEstruturaDescricao;
    }
    
    public void setTipoEstruturaDescricao(String tipoEstruturaDescricao) {
        this.tipoEstruturaDescricao = tipoEstruturaDescricao;
    }
    public Set getGaiolas() {
        return this.gaiolas;
    }
    
    public void setGaiolas(Set gaiolas) {
        this.gaiolas = gaiolas;
    }




}


