package model.dao;
// Generated 07/09/2016 21:42:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoFuncionario generated by hbm2java
 */
public class TipoFuncionario  implements java.io.Serializable {


     private Integer tipoFuncionarioCodigo;
     private String tipoFuncionarioDescricao;
     private Set funcionarios = new HashSet(0);

    public TipoFuncionario() {
    }

	
    public TipoFuncionario(String tipoFuncionarioDescricao) {
        this.tipoFuncionarioDescricao = tipoFuncionarioDescricao;
    }
    public TipoFuncionario(String tipoFuncionarioDescricao, Set funcionarios) {
       this.tipoFuncionarioDescricao = tipoFuncionarioDescricao;
       this.funcionarios = funcionarios;
    }
   
    public Integer getTipoFuncionarioCodigo() {
        return this.tipoFuncionarioCodigo;
    }
    
    public void setTipoFuncionarioCodigo(Integer tipoFuncionarioCodigo) {
        this.tipoFuncionarioCodigo = tipoFuncionarioCodigo;
    }
    public String getTipoFuncionarioDescricao() {
        return this.tipoFuncionarioDescricao;
    }
    
    public void setTipoFuncionarioDescricao(String tipoFuncionarioDescricao) {
        this.tipoFuncionarioDescricao = tipoFuncionarioDescricao;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }




}


