package model.dao;
// Generated 07/09/2016 21:42:17 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private Integer vendaCodigo;
     private Cliente cliente;
     private RegistraLotedepeixe registraLotedepeixe;
     private BigDecimal vendaValorTotalVenda;
     private Date vendaData;
     private Date vendaHora;
     private BigDecimal vendaPesoTotal;
     private Date vendaDataRegistro;

    public Venda() {
    }

    public Venda(Cliente cliente, RegistraLotedepeixe registraLotedepeixe, BigDecimal vendaValorTotalVenda, Date vendaData, Date vendaHora, BigDecimal vendaPesoTotal, Date vendaDataRegistro) {
       this.cliente = cliente;
       this.registraLotedepeixe = registraLotedepeixe;
       this.vendaValorTotalVenda = vendaValorTotalVenda;
       this.vendaData = vendaData;
       this.vendaHora = vendaHora;
       this.vendaPesoTotal = vendaPesoTotal;
       this.vendaDataRegistro = vendaDataRegistro;
    }
   
    public Integer getVendaCodigo() {
        return this.vendaCodigo;
    }
    
    public void setVendaCodigo(Integer vendaCodigo) {
        this.vendaCodigo = vendaCodigo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public RegistraLotedepeixe getRegistraLotedepeixe() {
        return this.registraLotedepeixe;
    }
    
    public void setRegistraLotedepeixe(RegistraLotedepeixe registraLotedepeixe) {
        this.registraLotedepeixe = registraLotedepeixe;
    }
    public BigDecimal getVendaValorTotalVenda() {
        return this.vendaValorTotalVenda;
    }
    
    public void setVendaValorTotalVenda(BigDecimal vendaValorTotalVenda) {
        this.vendaValorTotalVenda = vendaValorTotalVenda;
    }
    public Date getVendaData() {
        return this.vendaData;
    }
    
    public void setVendaData(Date vendaData) {
        this.vendaData = vendaData;
    }
    public Date getVendaHora() {
        return this.vendaHora;
    }
    
    public void setVendaHora(Date vendaHora) {
        this.vendaHora = vendaHora;
    }
    public BigDecimal getVendaPesoTotal() {
        return this.vendaPesoTotal;
    }
    
    public void setVendaPesoTotal(BigDecimal vendaPesoTotal) {
        this.vendaPesoTotal = vendaPesoTotal;
    }
    public Date getVendaDataRegistro() {
        return this.vendaDataRegistro;
    }
    
    public void setVendaDataRegistro(Date vendaDataRegistro) {
        this.vendaDataRegistro = vendaDataRegistro;
    }




}


