package model.bean;
// Generated 23/10/2016 17:38:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AlimentaHora generated by hbm2java
 */
@Entity
@Table(name="alimenta_hora"
    ,catalog="peixepontocom"
)
public class AlimentaHora  implements java.io.Serializable {


     private Integer alimentaHoraCodigo;
     private Date alimentaHoraHora;
     private Set alimentas = new HashSet(0);

    public AlimentaHora() {
    }

	
    public AlimentaHora(Date alimentaHoraHora) {
        this.alimentaHoraHora = alimentaHoraHora;
    }
    public AlimentaHora(Date alimentaHoraHora, Set alimentas) {
       this.alimentaHoraHora = alimentaHoraHora;
       this.alimentas = alimentas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="alimenta_Hora_Codigo", unique=true, nullable=false)
    public Integer getAlimentaHoraCodigo() {
        return this.alimentaHoraCodigo;
    }
    
    public void setAlimentaHoraCodigo(Integer alimentaHoraCodigo) {
        this.alimentaHoraCodigo = alimentaHoraCodigo;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="alimenta_Hora_Hora", nullable=false, length=8)
    public Date getAlimentaHoraHora() {
        return this.alimentaHoraHora;
    }
    
    public void setAlimentaHoraHora(Date alimentaHoraHora) {
        this.alimentaHoraHora = alimentaHoraHora;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="alimentaHora")
    public Set getAlimentas() {
        return this.alimentas;
    }
    
    public void setAlimentas(Set alimentas) {
        this.alimentas = alimentas;
    }




}


