package model.bean;
// Generated 23/10/2016 17:38:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bairros generated by hbm2java
 */
@Entity
@Table(name="bairros"
    ,catalog="peixepontocom"
)
public class Bairros  implements java.io.Serializable {


     private Integer bairroCodigo;
     private Cidades cidades;
     private String bairroNome;
     private Set clientes = new HashSet(0);
     private Set fornecedors = new HashSet(0);

    public Bairros() {
    }

	
    public Bairros(Cidades cidades, String bairroNome) {
        this.cidades = cidades;
        this.bairroNome = bairroNome;
    }
    public Bairros(Cidades cidades, String bairroNome, Set clientes, Set fornecedors) {
       this.cidades = cidades;
       this.bairroNome = bairroNome;
       this.clientes = clientes;
       this.fornecedors = fornecedors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="bairro_Codigo", unique=true, nullable=false)
    public Integer getBairroCodigo() {
        return this.bairroCodigo;
    }
    
    public void setBairroCodigo(Integer bairroCodigo) {
        this.bairroCodigo = bairroCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_B_cidades_codigo", nullable=false)
    public Cidades getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Cidades cidades) {
        this.cidades = cidades;
    }

    
    @Column(name="bairro_Nome", nullable=false, length=45)
    public String getBairroNome() {
        return this.bairroNome;
    }
    
    public void setBairroNome(String bairroNome) {
        this.bairroNome = bairroNome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bairros")
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bairros")
    public Set getFornecedors() {
        return this.fornecedors;
    }
    
    public void setFornecedors(Set fornecedors) {
        this.fornecedors = fornecedors;
    }




}


