package model.bean;
// Generated 18/10/2016 09:33:51 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Biometria generated by hbm2java
 */
@Entity
@Table(name="biometria"
    ,catalog="peixepontocom"
)
public class Biometria  implements java.io.Serializable {


     private Integer biometriaCodigo;
     private RegistraLotedepeixe registraLotedepeixe;
     private BigDecimal biometriaTotalQuilos;
     private int biometriaNumDaEtapa;
     private BigDecimal biometriaTaxaArracoamento;
     private Date biometriaDataBiometria;
     private Set realizas = new HashSet(0);
     private Set alimentas = new HashSet(0);

    public Biometria() {
    }

	
    public Biometria(RegistraLotedepeixe registraLotedepeixe, BigDecimal biometriaTotalQuilos, int biometriaNumDaEtapa, BigDecimal biometriaTaxaArracoamento, Date biometriaDataBiometria) {
        this.registraLotedepeixe = registraLotedepeixe;
        this.biometriaTotalQuilos = biometriaTotalQuilos;
        this.biometriaNumDaEtapa = biometriaNumDaEtapa;
        this.biometriaTaxaArracoamento = biometriaTaxaArracoamento;
        this.biometriaDataBiometria = biometriaDataBiometria;
    }
    public Biometria(RegistraLotedepeixe registraLotedepeixe, BigDecimal biometriaTotalQuilos, int biometriaNumDaEtapa, BigDecimal biometriaTaxaArracoamento, Date biometriaDataBiometria, Set realizas, Set alimentas) {
       this.registraLotedepeixe = registraLotedepeixe;
       this.biometriaTotalQuilos = biometriaTotalQuilos;
       this.biometriaNumDaEtapa = biometriaNumDaEtapa;
       this.biometriaTaxaArracoamento = biometriaTaxaArracoamento;
       this.biometriaDataBiometria = biometriaDataBiometria;
       this.realizas = realizas;
       this.alimentas = alimentas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="biometria_Codigo", unique=true, nullable=false)
    public Integer getBiometriaCodigo() {
        return this.biometriaCodigo;
    }
    
    public void setBiometriaCodigo(Integer biometriaCodigo) {
        this.biometriaCodigo = biometriaCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_B_registra_LoteDePeixe_Codigo", nullable=false)
    public RegistraLotedepeixe getRegistraLotedepeixe() {
        return this.registraLotedepeixe;
    }
    
    public void setRegistraLotedepeixe(RegistraLotedepeixe registraLotedepeixe) {
        this.registraLotedepeixe = registraLotedepeixe;
    }

    
    @Column(name="biometria_TotalQuilos", nullable=false, precision=10, scale=3)
    public BigDecimal getBiometriaTotalQuilos() {
        return this.biometriaTotalQuilos;
    }
    
    public void setBiometriaTotalQuilos(BigDecimal biometriaTotalQuilos) {
        this.biometriaTotalQuilos = biometriaTotalQuilos;
    }

    
    @Column(name="biometria_NumDaEtapa", nullable=false)
    public int getBiometriaNumDaEtapa() {
        return this.biometriaNumDaEtapa;
    }
    
    public void setBiometriaNumDaEtapa(int biometriaNumDaEtapa) {
        this.biometriaNumDaEtapa = biometriaNumDaEtapa;
    }

    
    @Column(name="biometria_TaxaArracoamento", nullable=false, precision=10, scale=3)
    public BigDecimal getBiometriaTaxaArracoamento() {
        return this.biometriaTaxaArracoamento;
    }
    
    public void setBiometriaTaxaArracoamento(BigDecimal biometriaTaxaArracoamento) {
        this.biometriaTaxaArracoamento = biometriaTaxaArracoamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="biometria_DataBiometria", nullable=false, length=10)
    public Date getBiometriaDataBiometria() {
        return this.biometriaDataBiometria;
    }
    
    public void setBiometriaDataBiometria(Date biometriaDataBiometria) {
        this.biometriaDataBiometria = biometriaDataBiometria;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="biometria")
    public Set getRealizas() {
        return this.realizas;
    }
    
    public void setRealizas(Set realizas) {
        this.realizas = realizas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="biometria")
    public Set getAlimentas() {
        return this.alimentas;
    }
    
    public void setAlimentas(Set alimentas) {
        this.alimentas = alimentas;
    }




}


