package model.bean;
// Generated 23/10/2016 17:38:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="peixepontocom"
)
public class Cliente  implements java.io.Serializable {


     private Integer clienteCodigo;
     private Bairros bairros;
     private String clienteCnpj;
     private String clienteNome;
     private String clienteEmail;
     private String clienteEndRua;
     private String clienteEndNumero;
     private Set telefoneClientes = new HashSet(0);
     private Set vendas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(Bairros bairros, String clienteCnpj, String clienteNome, String clienteEmail, String clienteEndRua, String clienteEndNumero) {
        this.bairros = bairros;
        this.clienteCnpj = clienteCnpj;
        this.clienteNome = clienteNome;
        this.clienteEmail = clienteEmail;
        this.clienteEndRua = clienteEndRua;
        this.clienteEndNumero = clienteEndNumero;
    }
    public Cliente(Bairros bairros, String clienteCnpj, String clienteNome, String clienteEmail, String clienteEndRua, String clienteEndNumero, Set telefoneClientes, Set vendas) {
       this.bairros = bairros;
       this.clienteCnpj = clienteCnpj;
       this.clienteNome = clienteNome;
       this.clienteEmail = clienteEmail;
       this.clienteEndRua = clienteEndRua;
       this.clienteEndNumero = clienteEndNumero;
       this.telefoneClientes = telefoneClientes;
       this.vendas = vendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cliente_Codigo", unique=true, nullable=false)
    public Integer getClienteCodigo() {
        return this.clienteCodigo;
    }
    
    public void setClienteCodigo(Integer clienteCodigo) {
        this.clienteCodigo = clienteCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_C_bairro_Codigo", nullable=false)
    public Bairros getBairros() {
        return this.bairros;
    }
    
    public void setBairros(Bairros bairros) {
        this.bairros = bairros;
    }

    
    @Column(name="cliente_CNPJ", nullable=false, length=18)
    public String getClienteCnpj() {
        return this.clienteCnpj;
    }
    
    public void setClienteCnpj(String clienteCnpj) {
        this.clienteCnpj = clienteCnpj;
    }

    
    @Column(name="cliente_Nome", nullable=false, length=50)
    public String getClienteNome() {
        return this.clienteNome;
    }
    
    public void setClienteNome(String clienteNome) {
        this.clienteNome = clienteNome;
    }

    
    @Column(name="cliente_Email", nullable=false, length=50)
    public String getClienteEmail() {
        return this.clienteEmail;
    }
    
    public void setClienteEmail(String clienteEmail) {
        this.clienteEmail = clienteEmail;
    }

    
    @Column(name="cliente_EndRua", nullable=false, length=120)
    public String getClienteEndRua() {
        return this.clienteEndRua;
    }
    
    public void setClienteEndRua(String clienteEndRua) {
        this.clienteEndRua = clienteEndRua;
    }

    
    @Column(name="cliente_EndNumero", nullable=false, length=6)
    public String getClienteEndNumero() {
        return this.clienteEndNumero;
    }
    
    public void setClienteEndNumero(String clienteEndNumero) {
        this.clienteEndNumero = clienteEndNumero;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getTelefoneClientes() {
        return this.telefoneClientes;
    }
    
    public void setTelefoneClientes(Set telefoneClientes) {
        this.telefoneClientes = telefoneClientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


