package model.bean;
// Generated 23/10/2016 17:38:25 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Fornece generated by hbm2java
 */
@Entity
@Table(name="fornece"
    ,catalog="peixepontocom"
)
public class Fornece  implements java.io.Serializable {


     private Integer forneceCodigo;
     private Fornecedor fornecedor;
     private Racao racao;
     private Integer forneceNumeroNf;
     private BigDecimal forneceQtdRacao;
     private BigDecimal forneceCustoDeCompra;

    public Fornece() {
    }

	
    public Fornece(Fornecedor fornecedor, Racao racao) {
        this.fornecedor = fornecedor;
        this.racao = racao;
    }
    public Fornece(Fornecedor fornecedor, Racao racao, Integer forneceNumeroNf, BigDecimal forneceQtdRacao, BigDecimal forneceCustoDeCompra) {
       this.fornecedor = fornecedor;
       this.racao = racao;
       this.forneceNumeroNf = forneceNumeroNf;
       this.forneceQtdRacao = forneceQtdRacao;
       this.forneceCustoDeCompra = forneceCustoDeCompra;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="fornece_Codigo", unique=true, nullable=false)
    public Integer getForneceCodigo() {
        return this.forneceCodigo;
    }
    
    public void setForneceCodigo(Integer forneceCodigo) {
        this.forneceCodigo = forneceCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_F_fornecedor_Codigo", nullable=false)
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_F_racao_Codigo", nullable=false)
    public Racao getRacao() {
        return this.racao;
    }
    
    public void setRacao(Racao racao) {
        this.racao = racao;
    }

    
    @Column(name="fornece_NumeroNF")
    public Integer getForneceNumeroNf() {
        return this.forneceNumeroNf;
    }
    
    public void setForneceNumeroNf(Integer forneceNumeroNf) {
        this.forneceNumeroNf = forneceNumeroNf;
    }

    
    @Column(name="fornece_QtdRacao", precision=10, scale=3)
    public BigDecimal getForneceQtdRacao() {
        return this.forneceQtdRacao;
    }
    
    public void setForneceQtdRacao(BigDecimal forneceQtdRacao) {
        this.forneceQtdRacao = forneceQtdRacao;
    }

    
    @Column(name="fornece_CustoDeCompra", precision=10)
    public BigDecimal getForneceCustoDeCompra() {
        return this.forneceCustoDeCompra;
    }
    
    public void setForneceCustoDeCompra(BigDecimal forneceCustoDeCompra) {
        this.forneceCustoDeCompra = forneceCustoDeCompra;
    }




}


