package model.bean;
// Generated 18/10/2016 09:33:51 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Fornecimentos generated by hbm2java
 */
@Entity
@Table(name="fornecimentos"
    ,catalog="peixepontocom"
)
public class Fornecimentos  implements java.io.Serializable {


     private Integer fornecimentosCodigo;
     private Fornecedor fornecedor;
     private Racao racao;
     private int fornecimentosNumeroNf;
     private BigDecimal fornecimentosQtdRacao;
     private BigDecimal fornecimentosCustoDeCompra;

    public Fornecimentos() {
    }

    public Fornecimentos(Fornecedor fornecedor, Racao racao, int fornecimentosNumeroNf, BigDecimal fornecimentosQtdRacao, BigDecimal fornecimentosCustoDeCompra) {
       this.fornecedor = fornecedor;
       this.racao = racao;
       this.fornecimentosNumeroNf = fornecimentosNumeroNf;
       this.fornecimentosQtdRacao = fornecimentosQtdRacao;
       this.fornecimentosCustoDeCompra = fornecimentosCustoDeCompra;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="fornecimentos_Codigo", unique=true, nullable=false)
    public Integer getFornecimentosCodigo() {
        return this.fornecimentosCodigo;
    }
    
    public void setFornecimentosCodigo(Integer fornecimentosCodigo) {
        this.fornecimentosCodigo = fornecimentosCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_F_fornecedor_Codigo", nullable=false)
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_F_racao_Codigo", nullable=false)
    public Racao getRacao() {
        return this.racao;
    }
    
    public void setRacao(Racao racao) {
        this.racao = racao;
    }

    
    @Column(name="fornecimentos_NumeroNF", nullable=false)
    public int getFornecimentosNumeroNf() {
        return this.fornecimentosNumeroNf;
    }
    
    public void setFornecimentosNumeroNf(int fornecimentosNumeroNf) {
        this.fornecimentosNumeroNf = fornecimentosNumeroNf;
    }

    
    @Column(name="fornecimentos_QtdRacao", nullable=false, precision=10, scale=3)
    public BigDecimal getFornecimentosQtdRacao() {
        return this.fornecimentosQtdRacao;
    }
    
    public void setFornecimentosQtdRacao(BigDecimal fornecimentosQtdRacao) {
        this.fornecimentosQtdRacao = fornecimentosQtdRacao;
    }

    
    @Column(name="fornecimentos_CustoDeCompra", nullable=false, precision=10)
    public BigDecimal getFornecimentosCustoDeCompra() {
        return this.fornecimentosCustoDeCompra;
    }
    
    public void setFornecimentosCustoDeCompra(BigDecimal fornecimentosCustoDeCompra) {
        this.fornecimentosCustoDeCompra = fornecimentosCustoDeCompra;
    }




}


