package model.bean;
// Generated 23/10/2016 17:38:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name="fornecedor"
    ,catalog="peixepontocom"
)
public class Fornecedor  implements java.io.Serializable {


     private Integer fornecedorCodigo;
     private Bairros bairros;
     private String fornecedorNomeFantasia;
     private String fornecedorRazaSocial;
     private String fornecedorCnpj;
     private String fornecedorEmail;
     private String fornecedorComentarios;
     private String fornecedorEndRua;
     private String fornecedorEndNumero;
     private Set telefoneFornecedors = new HashSet(0);
     private Set forneces = new HashSet(0);

    public Fornecedor() {
    }

	
    public Fornecedor(Bairros bairros, String fornecedorNomeFantasia, String fornecedorRazaSocial, String fornecedorCnpj, String fornecedorEmail, String fornecedorEndRua, String fornecedorEndNumero) {
        this.bairros = bairros;
        this.fornecedorNomeFantasia = fornecedorNomeFantasia;
        this.fornecedorRazaSocial = fornecedorRazaSocial;
        this.fornecedorCnpj = fornecedorCnpj;
        this.fornecedorEmail = fornecedorEmail;
        this.fornecedorEndRua = fornecedorEndRua;
        this.fornecedorEndNumero = fornecedorEndNumero;
    }
    public Fornecedor(Bairros bairros, String fornecedorNomeFantasia, String fornecedorRazaSocial, String fornecedorCnpj, String fornecedorEmail, String fornecedorComentarios, String fornecedorEndRua, String fornecedorEndNumero, Set telefoneFornecedors, Set forneces) {
       this.bairros = bairros;
       this.fornecedorNomeFantasia = fornecedorNomeFantasia;
       this.fornecedorRazaSocial = fornecedorRazaSocial;
       this.fornecedorCnpj = fornecedorCnpj;
       this.fornecedorEmail = fornecedorEmail;
       this.fornecedorComentarios = fornecedorComentarios;
       this.fornecedorEndRua = fornecedorEndRua;
       this.fornecedorEndNumero = fornecedorEndNumero;
       this.telefoneFornecedors = telefoneFornecedors;
       this.forneces = forneces;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="fornecedor_Codigo", unique=true, nullable=false)
    public Integer getFornecedorCodigo() {
        return this.fornecedorCodigo;
    }
    
    public void setFornecedorCodigo(Integer fornecedorCodigo) {
        this.fornecedorCodigo = fornecedorCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_F_bairro_Codigo", nullable=false)
    public Bairros getBairros() {
        return this.bairros;
    }
    
    public void setBairros(Bairros bairros) {
        this.bairros = bairros;
    }

    
    @Column(name="fornecedor_NomeFantasia", nullable=false, length=45)
    public String getFornecedorNomeFantasia() {
        return this.fornecedorNomeFantasia;
    }
    
    public void setFornecedorNomeFantasia(String fornecedorNomeFantasia) {
        this.fornecedorNomeFantasia = fornecedorNomeFantasia;
    }

    
    @Column(name="fornecedor_RazaSocial", nullable=false, length=45)
    public String getFornecedorRazaSocial() {
        return this.fornecedorRazaSocial;
    }
    
    public void setFornecedorRazaSocial(String fornecedorRazaSocial) {
        this.fornecedorRazaSocial = fornecedorRazaSocial;
    }

    
    @Column(name="fornecedor_CNPJ", nullable=false, length=18)
    public String getFornecedorCnpj() {
        return this.fornecedorCnpj;
    }
    
    public void setFornecedorCnpj(String fornecedorCnpj) {
        this.fornecedorCnpj = fornecedorCnpj;
    }

    
    @Column(name="fornecedor_Email", nullable=false, length=45)
    public String getFornecedorEmail() {
        return this.fornecedorEmail;
    }
    
    public void setFornecedorEmail(String fornecedorEmail) {
        this.fornecedorEmail = fornecedorEmail;
    }

    
    @Column(name="fornecedor_Comentarios")
    public String getFornecedorComentarios() {
        return this.fornecedorComentarios;
    }
    
    public void setFornecedorComentarios(String fornecedorComentarios) {
        this.fornecedorComentarios = fornecedorComentarios;
    }

    
    @Column(name="fornecedor_EndRua", nullable=false, length=120)
    public String getFornecedorEndRua() {
        return this.fornecedorEndRua;
    }
    
    public void setFornecedorEndRua(String fornecedorEndRua) {
        this.fornecedorEndRua = fornecedorEndRua;
    }

    
    @Column(name="fornecedor_EndNumero", nullable=false, length=6)
    public String getFornecedorEndNumero() {
        return this.fornecedorEndNumero;
    }
    
    public void setFornecedorEndNumero(String fornecedorEndNumero) {
        this.fornecedorEndNumero = fornecedorEndNumero;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedor")
    public Set getTelefoneFornecedors() {
        return this.telefoneFornecedors;
    }
    
    public void setTelefoneFornecedors(Set telefoneFornecedors) {
        this.telefoneFornecedors = telefoneFornecedors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedor")
    public Set getForneces() {
        return this.forneces;
    }
    
    public void setForneces(Set forneces) {
        this.forneces = forneces;
    }




}


