package model.bean;
// Generated 23/10/2016 17:38:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Funcionario generated by hbm2java
 */
@Entity
@Table(name="funcionario"
    ,catalog="peixepontocom"
)
public class Funcionario  implements java.io.Serializable {


     private Integer funcionarioCodigo;
     private TipoFuncionario tipoFuncionario;
     private String funcionarioNome;
     private String funcionarioEmail;
     private String funcionarioTelDddfixo;
     private String funcionarioTelFixo;
     private String funcionarioTelDddcelular;
     private String funcionarioTelCelular;
     private String funcionarioUsuLogin;
     private String funcionarioUsuSenha;
     private boolean funcionarioAtivo;
     private Set registraLotedepeixes = new HashSet(0);
     private Set biometriaPeixeItems = new HashSet(0);
     private Set notificacaos = new HashSet(0);

    public Funcionario() {
    }

    public boolean verificaUsuario(){
        
        if(this.funcionarioUsuLogin!=null && this.funcionarioUsuSenha!=null){
            if(this.funcionarioUsuLogin.equals("thiago") && this.funcionarioUsuSenha.equals("1234")){
                return true;
            }
        }
        return false;
    }
    
    public Funcionario(TipoFuncionario tipoFuncionario, String funcionarioNome, String funcionarioEmail, boolean funcionarioAtivo) {
        this.tipoFuncionario = tipoFuncionario;
        this.funcionarioNome = funcionarioNome;
        this.funcionarioEmail = funcionarioEmail;
        this.funcionarioAtivo = funcionarioAtivo;
    }
    public Funcionario(TipoFuncionario tipoFuncionario, String funcionarioNome, String funcionarioEmail, String funcionarioTelDddfixo, String funcionarioTelFixo, String funcionarioTelDddcelular, String funcionarioTelCelular, String funcionarioUsuLogin, String funcionarioUsuSenha, boolean funcionarioAtivo, Set registraLotedepeixes, Set biometriaPeixeItems, Set notificacaos) {
       this.tipoFuncionario = tipoFuncionario;
       this.funcionarioNome = funcionarioNome;
       this.funcionarioEmail = funcionarioEmail;
       this.funcionarioTelDddfixo = funcionarioTelDddfixo;
       this.funcionarioTelFixo = funcionarioTelFixo;
       this.funcionarioTelDddcelular = funcionarioTelDddcelular;
       this.funcionarioTelCelular = funcionarioTelCelular;
       this.funcionarioUsuLogin = funcionarioUsuLogin;
       this.funcionarioUsuSenha = funcionarioUsuSenha;
       this.funcionarioAtivo = funcionarioAtivo;
       this.registraLotedepeixes = registraLotedepeixes;
       this.biometriaPeixeItems = biometriaPeixeItems;
       this.notificacaos = notificacaos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="funcionario_Codigo", unique=true, nullable=false)
    public Integer getFuncionarioCodigo() {
        return this.funcionarioCodigo;
    }
    
    public void setFuncionarioCodigo(Integer funcionarioCodigo) {
        this.funcionarioCodigo = funcionarioCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_F_tipo_Funcionario_Codigo", nullable=false)
    public TipoFuncionario getTipoFuncionario() {
        return this.tipoFuncionario;
    }
    
    public void setTipoFuncionario(TipoFuncionario tipoFuncionario) {
        this.tipoFuncionario = tipoFuncionario;
    }

    
    @Column(name="funcionario_Nome", nullable=false, length=45)
    public String getFuncionarioNome() {
        return this.funcionarioNome;
    }
    
    public void setFuncionarioNome(String funcionarioNome) {
        this.funcionarioNome = funcionarioNome;
    }

    
    @Column(name="funcionario_Email", nullable=false, length=45)
    public String getFuncionarioEmail() {
        return this.funcionarioEmail;
    }
    
    public void setFuncionarioEmail(String funcionarioEmail) {
        this.funcionarioEmail = funcionarioEmail;
    }

    
    @Column(name="funcionario_telDDDFixo", length=3)
    public String getFuncionarioTelDddfixo() {
        return this.funcionarioTelDddfixo;
    }
    
    public void setFuncionarioTelDddfixo(String funcionarioTelDddfixo) {
        this.funcionarioTelDddfixo = funcionarioTelDddfixo;
    }

    
    @Column(name="funcionario_telFixo", length=10)
    public String getFuncionarioTelFixo() {
        return this.funcionarioTelFixo;
    }
    
    public void setFuncionarioTelFixo(String funcionarioTelFixo) {
        this.funcionarioTelFixo = funcionarioTelFixo;
    }

    
    @Column(name="funcionario_telDDDCelular", length=3)
    public String getFuncionarioTelDddcelular() {
        return this.funcionarioTelDddcelular;
    }
    
    public void setFuncionarioTelDddcelular(String funcionarioTelDddcelular) {
        this.funcionarioTelDddcelular = funcionarioTelDddcelular;
    }

    
    @Column(name="funcionario_telCelular", length=10)
    public String getFuncionarioTelCelular() {
        return this.funcionarioTelCelular;
    }
    
    public void setFuncionarioTelCelular(String funcionarioTelCelular) {
        this.funcionarioTelCelular = funcionarioTelCelular;
    }

    
    @Column(name="funcionario_usuLogin", length=45)
    public String getFuncionarioUsuLogin() {
        return this.funcionarioUsuLogin;
    }
    
    public void setFuncionarioUsuLogin(String funcionarioUsuLogin) {
        this.funcionarioUsuLogin = funcionarioUsuLogin;
    }

    
    @Column(name="funcionario_usuSenha", length=32)
    public String getFuncionarioUsuSenha() {
        return this.funcionarioUsuSenha;
    }
    
    public void setFuncionarioUsuSenha(String funcionarioUsuSenha) {
        this.funcionarioUsuSenha = funcionarioUsuSenha;
    }

    
    @Column(name="funcionario_Ativo", nullable=false)
    public boolean isFuncionarioAtivo() {
        return this.funcionarioAtivo;
    }
    
    public void setFuncionarioAtivo(boolean funcionarioAtivo) {
        this.funcionarioAtivo = funcionarioAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="funcionario")
    public Set getRegistraLotedepeixes() {
        return this.registraLotedepeixes;
    }
    
    public void setRegistraLotedepeixes(Set registraLotedepeixes) {
        this.registraLotedepeixes = registraLotedepeixes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="funcionario")
    public Set getBiometriaPeixeItems() {
        return this.biometriaPeixeItems;
    }
    
    public void setBiometriaPeixeItems(Set biometriaPeixeItems) {
        this.biometriaPeixeItems = biometriaPeixeItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="funcionario")
    public Set getNotificacaos() {
        return this.notificacaos;
    }
    
    public void setNotificacaos(Set notificacaos) {
        this.notificacaos = notificacaos;
    }




}


