package model.bean;
// Generated 13/10/2016 17:42:16 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NotificacaoId generated by hbm2java
 */
@Embeddable
public class NotificacaoId  implements java.io.Serializable {


     private int notificacaoCodigo;
     private int fkTnFuncionarioCodigo;

    public NotificacaoId() {
    }

    public NotificacaoId(int notificacaoCodigo, int fkTnFuncionarioCodigo) {
       this.notificacaoCodigo = notificacaoCodigo;
       this.fkTnFuncionarioCodigo = fkTnFuncionarioCodigo;
    }
   


    @Column(name="notificacao_Codigo", nullable=false)
    public int getNotificacaoCodigo() {
        return this.notificacaoCodigo;
    }
    
    public void setNotificacaoCodigo(int notificacaoCodigo) {
        this.notificacaoCodigo = notificacaoCodigo;
    }


    @Column(name="fk_TN_funcionario_Codigo", nullable=false)
    public int getFkTnFuncionarioCodigo() {
        return this.fkTnFuncionarioCodigo;
    }
    
    public void setFkTnFuncionarioCodigo(int fkTnFuncionarioCodigo) {
        this.fkTnFuncionarioCodigo = fkTnFuncionarioCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NotificacaoId) ) return false;
		 NotificacaoId castOther = ( NotificacaoId ) other; 
         
		 return (this.getNotificacaoCodigo()==castOther.getNotificacaoCodigo())
 && (this.getFkTnFuncionarioCodigo()==castOther.getFkTnFuncionarioCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNotificacaoCodigo();
         result = 37 * result + this.getFkTnFuncionarioCodigo();
         return result;
   }   


}


