package model.bean;
// Generated 01/10/2016 13:14:33 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Notificacoes generated by hbm2java
 */
@Entity
@Table(name="notificacoes"
    ,catalog="peixepontocom"
)
public class Notificacoes  implements java.io.Serializable {


     private Integer notificacoesCodigo;
     private TipoNotificacoes tipoNotificacoes;
     private String notificacoesDescricao;

    public Notificacoes() {
    }

    public Notificacoes(TipoNotificacoes tipoNotificacoes, String notificacoesDescricao) {
       this.tipoNotificacoes = tipoNotificacoes;
       this.notificacoesDescricao = notificacoesDescricao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="notificacoes_Codigo", unique=true, nullable=false)
    public Integer getNotificacoesCodigo() {
        return this.notificacoesCodigo;
    }
    
    public void setNotificacoesCodigo(Integer notificacoesCodigo) {
        this.notificacoesCodigo = notificacoesCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_TN_tipo_Notificacoes_Codigo", nullable=false)
    public TipoNotificacoes getTipoNotificacoes() {
        return this.tipoNotificacoes;
    }
    
    public void setTipoNotificacoes(TipoNotificacoes tipoNotificacoes) {
        this.tipoNotificacoes = tipoNotificacoes;
    }

    
    @Column(name="notificacoes_Descricao", nullable=false)
    public String getNotificacoesDescricao() {
        return this.notificacoesDescricao;
    }
    
    public void setNotificacoesDescricao(String notificacoesDescricao) {
        this.notificacoesDescricao = notificacoesDescricao;
    }




}


