package model.bean;
// Generated 23/10/2016 17:38:25 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notificacao generated by hbm2java
 */
@Entity
@Table(name="notificacao"
    ,catalog="peixepontocom"
)
public class Notificacao  implements java.io.Serializable {


     private Integer notificacaoCodigo;
     private Funcionario funcionario;
     private TipoNotificacao tipoNotificacao;
     private String notificacaoTitulo;
     private String notificacaoDescricao;
     private Date notificacaoData;
     private Date notificacaoHora;

    public Notificacao() {
    }

    public Notificacao(Funcionario funcionario, TipoNotificacao tipoNotificacao, String notificacaoTitulo, String notificacaoDescricao, Date notificacaoData, Date notificacaoHora) {
       this.funcionario = funcionario;
       this.tipoNotificacao = tipoNotificacao;
       this.notificacaoTitulo = notificacaoTitulo;
       this.notificacaoDescricao = notificacaoDescricao;
       this.notificacaoData = notificacaoData;
       this.notificacaoHora = notificacaoHora;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="notificacao_Codigo", unique=true, nullable=false)
    public Integer getNotificacaoCodigo() {
        return this.notificacaoCodigo;
    }
    
    public void setNotificacaoCodigo(Integer notificacaoCodigo) {
        this.notificacaoCodigo = notificacaoCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Tn_funcionario_Codigo", nullable=false)
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Tn_tipo_Notificacao_Codigo", nullable=false)
    public TipoNotificacao getTipoNotificacao() {
        return this.tipoNotificacao;
    }
    
    public void setTipoNotificacao(TipoNotificacao tipoNotificacao) {
        this.tipoNotificacao = tipoNotificacao;
    }

    
    @Column(name="notificacao_Titulo", nullable=false, length=45)
    public String getNotificacaoTitulo() {
        return this.notificacaoTitulo;
    }
    
    public void setNotificacaoTitulo(String notificacaoTitulo) {
        this.notificacaoTitulo = notificacaoTitulo;
    }

    
    @Column(name="notificacao_Descricao", nullable=false)
    public String getNotificacaoDescricao() {
        return this.notificacaoDescricao;
    }
    
    public void setNotificacaoDescricao(String notificacaoDescricao) {
        this.notificacaoDescricao = notificacaoDescricao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="notificacao_Data", nullable=false, length=10)
    public Date getNotificacaoData() {
        return this.notificacaoData;
    }
    
    public void setNotificacaoData(Date notificacaoData) {
        this.notificacaoData = notificacaoData;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="notificacao_Hora", nullable=false, length=8)
    public Date getNotificacaoHora() {
        return this.notificacaoHora;
    }
    
    public void setNotificacaoHora(Date notificacaoHora) {
        this.notificacaoHora = notificacaoHora;
    }




}


