package model.bean;
// Generated 18/10/2016 09:33:51 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Realiza generated by hbm2java
 */
@Entity
@Table(name="realiza"
    ,catalog="peixepontocom"
)
public class Realiza  implements java.io.Serializable {


     private Integer realizaCodigo;
     private Biometria biometria;
     private Funcionario funcionario;
     private BigDecimal realizaPeso;
     private BigDecimal realizaTamanho;

    public Realiza() {
    }

    public Realiza(Biometria biometria, Funcionario funcionario, BigDecimal realizaPeso, BigDecimal realizaTamanho) {
       this.biometria = biometria;
       this.funcionario = funcionario;
       this.realizaPeso = realizaPeso;
       this.realizaTamanho = realizaTamanho;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="realiza_Codigo", unique=true, nullable=false)
    public Integer getRealizaCodigo() {
        return this.realizaCodigo;
    }
    
    public void setRealizaCodigo(Integer realizaCodigo) {
        this.realizaCodigo = realizaCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_R_Biometria_Codigo", nullable=false)
    public Biometria getBiometria() {
        return this.biometria;
    }
    
    public void setBiometria(Biometria biometria) {
        this.biometria = biometria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_R_Funcionario_Codigo", nullable=false)
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

    
    @Column(name="realiza_Peso", nullable=false, precision=10, scale=3)
    public BigDecimal getRealizaPeso() {
        return this.realizaPeso;
    }
    
    public void setRealizaPeso(BigDecimal realizaPeso) {
        this.realizaPeso = realizaPeso;
    }

    
    @Column(name="realiza_Tamanho", nullable=false, precision=10, scale=3)
    public BigDecimal getRealizaTamanho() {
        return this.realizaTamanho;
    }
    
    public void setRealizaTamanho(BigDecimal realizaTamanho) {
        this.realizaTamanho = realizaTamanho;
    }




}


