package model.bean;
// Generated 23/10/2016 17:38:25 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegistraLotedepeixe generated by hbm2java
 */
@Entity
@Table(name="registra_lotedepeixe"
    ,catalog="peixepontocom"
)
public class RegistraLotedepeixe  implements java.io.Serializable {


     private Integer registraLoteDePeixeCodigo;
     private Funcionario funcionario;
     private Gaiola gaiola;
     private TipoPeixes tipoPeixes;
     private int registraLoteDePeixeQtdMaxM3;
     private double registraLoteDePeixeQuantidade;
     private BigDecimal registraLoteDePeixeCustoLote;
     private Date registraLoteDePeixeDataDeRegistro;
     private boolean registraLoteDePeixeAtivo;
     private Set biometriaPeixeItems = new HashSet(0);
     private Set vendas = new HashSet(0);

    public RegistraLotedepeixe() {
    }

	
    public RegistraLotedepeixe(Funcionario funcionario, Gaiola gaiola, TipoPeixes tipoPeixes, int registraLoteDePeixeQtdMaxM3, double registraLoteDePeixeQuantidade, BigDecimal registraLoteDePeixeCustoLote, Date registraLoteDePeixeDataDeRegistro, boolean registraLoteDePeixeAtivo) {
        this.funcionario = funcionario;
        this.gaiola = gaiola;
        this.tipoPeixes = tipoPeixes;
        this.registraLoteDePeixeQtdMaxM3 = registraLoteDePeixeQtdMaxM3;
        this.registraLoteDePeixeQuantidade = registraLoteDePeixeQuantidade;
        this.registraLoteDePeixeCustoLote = registraLoteDePeixeCustoLote;
        this.registraLoteDePeixeDataDeRegistro = registraLoteDePeixeDataDeRegistro;
        this.registraLoteDePeixeAtivo = registraLoteDePeixeAtivo;
    }
    public RegistraLotedepeixe(Funcionario funcionario, Gaiola gaiola, TipoPeixes tipoPeixes, int registraLoteDePeixeQtdMaxM3, double registraLoteDePeixeQuantidade, BigDecimal registraLoteDePeixeCustoLote, Date registraLoteDePeixeDataDeRegistro, boolean registraLoteDePeixeAtivo, Set biometriaPeixeItems, Set vendas) {
       this.funcionario = funcionario;
       this.gaiola = gaiola;
       this.tipoPeixes = tipoPeixes;
       this.registraLoteDePeixeQtdMaxM3 = registraLoteDePeixeQtdMaxM3;
       this.registraLoteDePeixeQuantidade = registraLoteDePeixeQuantidade;
       this.registraLoteDePeixeCustoLote = registraLoteDePeixeCustoLote;
       this.registraLoteDePeixeDataDeRegistro = registraLoteDePeixeDataDeRegistro;
       this.registraLoteDePeixeAtivo = registraLoteDePeixeAtivo;
       this.biometriaPeixeItems = biometriaPeixeItems;
       this.vendas = vendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="registra_LoteDePeixe_Codigo", unique=true, nullable=false)
    public Integer getRegistraLoteDePeixeCodigo() {
        return this.registraLoteDePeixeCodigo;
    }
    
    public void setRegistraLoteDePeixeCodigo(Integer registraLoteDePeixeCodigo) {
        this.registraLoteDePeixeCodigo = registraLoteDePeixeCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Rl_Funcionario_Codigo", nullable=false)
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Rl_Gaiola_Codigo", nullable=false)
    public Gaiola getGaiola() {
        return this.gaiola;
    }
    
    public void setGaiola(Gaiola gaiola) {
        this.gaiola = gaiola;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Rl_Tipo_Peixes_Codigo", nullable=false)
    public TipoPeixes getTipoPeixes() {
        return this.tipoPeixes;
    }
    
    public void setTipoPeixes(TipoPeixes tipoPeixes) {
        this.tipoPeixes = tipoPeixes;
    }

    
    @Column(name="registra_LoteDePeixe_QtdMaxM3", nullable=false)
    public int getRegistraLoteDePeixeQtdMaxM3() {
        return this.registraLoteDePeixeQtdMaxM3;
    }
    
    public void setRegistraLoteDePeixeQtdMaxM3(int registraLoteDePeixeQtdMaxM3) {
        this.registraLoteDePeixeQtdMaxM3 = registraLoteDePeixeQtdMaxM3;
    }

    
    @Column(name="registra_LoteDePeixe_Quantidade", nullable=false, precision=22, scale=0)
    public double getRegistraLoteDePeixeQuantidade() {
        return this.registraLoteDePeixeQuantidade;
    }
    
    public void setRegistraLoteDePeixeQuantidade(double registraLoteDePeixeQuantidade) {
        this.registraLoteDePeixeQuantidade = registraLoteDePeixeQuantidade;
    }

    
    @Column(name="registra_LoteDePeixe_CustoLote", nullable=false, precision=10)
    public BigDecimal getRegistraLoteDePeixeCustoLote() {
        return this.registraLoteDePeixeCustoLote;
    }
    
    public void setRegistraLoteDePeixeCustoLote(BigDecimal registraLoteDePeixeCustoLote) {
        this.registraLoteDePeixeCustoLote = registraLoteDePeixeCustoLote;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="registra_LoteDePeixe_DataDeRegistro", nullable=false, length=10)
    public Date getRegistraLoteDePeixeDataDeRegistro() {
        return this.registraLoteDePeixeDataDeRegistro;
    }
    
    public void setRegistraLoteDePeixeDataDeRegistro(Date registraLoteDePeixeDataDeRegistro) {
        this.registraLoteDePeixeDataDeRegistro = registraLoteDePeixeDataDeRegistro;
    }

    
    @Column(name="registra_LoteDePeixe_Ativo", nullable=false)
    public boolean isRegistraLoteDePeixeAtivo() {
        return this.registraLoteDePeixeAtivo;
    }
    
    public void setRegistraLoteDePeixeAtivo(boolean registraLoteDePeixeAtivo) {
        this.registraLoteDePeixeAtivo = registraLoteDePeixeAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="registraLotedepeixe")
    public Set getBiometriaPeixeItems() {
        return this.biometriaPeixeItems;
    }
    
    public void setBiometriaPeixeItems(Set biometriaPeixeItems) {
        this.biometriaPeixeItems = biometriaPeixeItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="registraLotedepeixe")
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


