package model.bean;
// Generated 23/10/2016 17:38:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StatusGaiola generated by hbm2java
 */
@Entity
@Table(name="status_gaiola"
    ,catalog="peixepontocom"
)
public class StatusGaiola  implements java.io.Serializable {


     private Integer statusGaiolaCodigo;
     private String statusGaiolaDescricao;
     private String statusGaiolaClass;
     private Set gaiolas = new HashSet(0);

    public StatusGaiola() {
    }

	
    public StatusGaiola(String statusGaiolaDescricao) {
        this.statusGaiolaDescricao = statusGaiolaDescricao;
    }
    public StatusGaiola(String statusGaiolaDescricao, String statusGaiolaClass, Set gaiolas) {
       this.statusGaiolaDescricao = statusGaiolaDescricao;
       this.statusGaiolaClass = statusGaiolaClass;
       this.gaiolas = gaiolas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="status_Gaiola_Codigo", unique=true, nullable=false)
    public Integer getStatusGaiolaCodigo() {
        return this.statusGaiolaCodigo;
    }
    
    public void setStatusGaiolaCodigo(Integer statusGaiolaCodigo) {
        this.statusGaiolaCodigo = statusGaiolaCodigo;
    }

    
    @Column(name="status_Gaiola_Descricao", nullable=false, length=45)
    public String getStatusGaiolaDescricao() {
        return this.statusGaiolaDescricao;
    }
    
    public void setStatusGaiolaDescricao(String statusGaiolaDescricao) {
        this.statusGaiolaDescricao = statusGaiolaDescricao;
    }

    
    @Column(name="status_Gaiola_class", length=45)
    public String getStatusGaiolaClass() {
        return this.statusGaiolaClass;
    }
    
    public void setStatusGaiolaClass(String statusGaiolaClass) {
        this.statusGaiolaClass = statusGaiolaClass;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="statusGaiola")
    public Set getGaiolas() {
        return this.gaiolas;
    }
    
    public void setGaiolas(Set gaiolas) {
        this.gaiolas = gaiolas;
    }




}


