package model.bean;
// Generated 23/10/2016 17:38:25 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaxaDeAlimentacao generated by hbm2java
 */
@Entity
@Table(name="taxa_de_alimentacao"
    ,catalog="peixepontocom"
)
public class TaxaDeAlimentacao  implements java.io.Serializable {


     private Integer taxaDeAlimentacaoCodigo;
     private BigDecimal taxaDeAlimentacaoTaxa;
     private BigDecimal taxaDeAlimentacaoPesoMinimo;
     private BigDecimal taxaDeAlimentacaoPesoMaximo;
     private Set biometriaPeixeItems = new HashSet(0);

    public TaxaDeAlimentacao() {
    }

	
    public TaxaDeAlimentacao(BigDecimal taxaDeAlimentacaoTaxa, BigDecimal taxaDeAlimentacaoPesoMinimo, BigDecimal taxaDeAlimentacaoPesoMaximo) {
        this.taxaDeAlimentacaoTaxa = taxaDeAlimentacaoTaxa;
        this.taxaDeAlimentacaoPesoMinimo = taxaDeAlimentacaoPesoMinimo;
        this.taxaDeAlimentacaoPesoMaximo = taxaDeAlimentacaoPesoMaximo;
    }
    public TaxaDeAlimentacao(BigDecimal taxaDeAlimentacaoTaxa, BigDecimal taxaDeAlimentacaoPesoMinimo, BigDecimal taxaDeAlimentacaoPesoMaximo, Set biometriaPeixeItems) {
       this.taxaDeAlimentacaoTaxa = taxaDeAlimentacaoTaxa;
       this.taxaDeAlimentacaoPesoMinimo = taxaDeAlimentacaoPesoMinimo;
       this.taxaDeAlimentacaoPesoMaximo = taxaDeAlimentacaoPesoMaximo;
       this.biometriaPeixeItems = biometriaPeixeItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="taxa_De_Alimentacao_Codigo", unique=true, nullable=false)
    public Integer getTaxaDeAlimentacaoCodigo() {
        return this.taxaDeAlimentacaoCodigo;
    }
    
    public void setTaxaDeAlimentacaoCodigo(Integer taxaDeAlimentacaoCodigo) {
        this.taxaDeAlimentacaoCodigo = taxaDeAlimentacaoCodigo;
    }

    
    @Column(name="taxa_De_Alimentacao_Taxa", nullable=false, precision=10, scale=4)
    public BigDecimal getTaxaDeAlimentacaoTaxa() {
        return this.taxaDeAlimentacaoTaxa;
    }
    
    public void setTaxaDeAlimentacaoTaxa(BigDecimal taxaDeAlimentacaoTaxa) {
        this.taxaDeAlimentacaoTaxa = taxaDeAlimentacaoTaxa;
    }

    
    @Column(name="taxa_De_Alimentacao_Peso_Minimo", nullable=false, precision=10, scale=3)
    public BigDecimal getTaxaDeAlimentacaoPesoMinimo() {
        return this.taxaDeAlimentacaoPesoMinimo;
    }
    
    public void setTaxaDeAlimentacaoPesoMinimo(BigDecimal taxaDeAlimentacaoPesoMinimo) {
        this.taxaDeAlimentacaoPesoMinimo = taxaDeAlimentacaoPesoMinimo;
    }

    
    @Column(name="taxa_De_Alimentacao_Peso_Maximo", nullable=false, precision=10, scale=3)
    public BigDecimal getTaxaDeAlimentacaoPesoMaximo() {
        return this.taxaDeAlimentacaoPesoMaximo;
    }
    
    public void setTaxaDeAlimentacaoPesoMaximo(BigDecimal taxaDeAlimentacaoPesoMaximo) {
        this.taxaDeAlimentacaoPesoMaximo = taxaDeAlimentacaoPesoMaximo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taxaDeAlimentacao")
    public Set getBiometriaPeixeItems() {
        return this.biometriaPeixeItems;
    }
    
    public void setBiometriaPeixeItems(Set biometriaPeixeItems) {
        this.biometriaPeixeItems = biometriaPeixeItems;
    }




}


