package model.bean;
// Generated 23/10/2016 17:38:25 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TelefoneFornecedor generated by hbm2java
 */
@Entity
@Table(name="telefone_fornecedor"
    ,catalog="peixepontocom"
)
public class TelefoneFornecedor  implements java.io.Serializable {


     private Integer telefoneFornecedorCodigo;
     private Fornecedor fornecedor;
     private String telefoneFornecedorDddfixo;
     private String telefoneFornecedorFixo;
     private String telefoneFornecedorDddcelular;
     private String telefoneFornecedorCelular;

    public TelefoneFornecedor() {
    }

	
    public TelefoneFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public TelefoneFornecedor(Fornecedor fornecedor, String telefoneFornecedorDddfixo, String telefoneFornecedorFixo, String telefoneFornecedorDddcelular, String telefoneFornecedorCelular) {
       this.fornecedor = fornecedor;
       this.telefoneFornecedorDddfixo = telefoneFornecedorDddfixo;
       this.telefoneFornecedorFixo = telefoneFornecedorFixo;
       this.telefoneFornecedorDddcelular = telefoneFornecedorDddcelular;
       this.telefoneFornecedorCelular = telefoneFornecedorCelular;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="telefone_Fornecedor_Codigo", unique=true, nullable=false)
    public Integer getTelefoneFornecedorCodigo() {
        return this.telefoneFornecedorCodigo;
    }
    
    public void setTelefoneFornecedorCodigo(Integer telefoneFornecedorCodigo) {
        this.telefoneFornecedorCodigo = telefoneFornecedorCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Tf_Fornecedor_Codigo", nullable=false)
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }

    
    @Column(name="telefone_Fornecedor_DDDFixo", length=3)
    public String getTelefoneFornecedorDddfixo() {
        return this.telefoneFornecedorDddfixo;
    }
    
    public void setTelefoneFornecedorDddfixo(String telefoneFornecedorDddfixo) {
        this.telefoneFornecedorDddfixo = telefoneFornecedorDddfixo;
    }

    
    @Column(name="telefone_Fornecedor_Fixo", length=10)
    public String getTelefoneFornecedorFixo() {
        return this.telefoneFornecedorFixo;
    }
    
    public void setTelefoneFornecedorFixo(String telefoneFornecedorFixo) {
        this.telefoneFornecedorFixo = telefoneFornecedorFixo;
    }

    
    @Column(name="telefone_Fornecedor_DDDCelular", length=3)
    public String getTelefoneFornecedorDddcelular() {
        return this.telefoneFornecedorDddcelular;
    }
    
    public void setTelefoneFornecedorDddcelular(String telefoneFornecedorDddcelular) {
        this.telefoneFornecedorDddcelular = telefoneFornecedorDddcelular;
    }

    
    @Column(name="telefone_Fornecedor_Celular", length=10)
    public String getTelefoneFornecedorCelular() {
        return this.telefoneFornecedorCelular;
    }
    
    public void setTelefoneFornecedorCelular(String telefoneFornecedorCelular) {
        this.telefoneFornecedorCelular = telefoneFornecedorCelular;
    }




}


