package model.bean;
// Generated 01/10/2016 13:14:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoNotificacoes generated by hbm2java
 */
@Entity
@Table(name="tipo_notificacoes"
    ,catalog="peixepontocom"
)
public class TipoNotificacoes  implements java.io.Serializable {


     private Integer tipoNotificacoesCodigo;
     private String tipoNotificacoesDescricao;
     private Set notificacoeses = new HashSet(0);

    public TipoNotificacoes() {
    }

	
    public TipoNotificacoes(String tipoNotificacoesDescricao) {
        this.tipoNotificacoesDescricao = tipoNotificacoesDescricao;
    }
    public TipoNotificacoes(String tipoNotificacoesDescricao, Set notificacoeses) {
       this.tipoNotificacoesDescricao = tipoNotificacoesDescricao;
       this.notificacoeses = notificacoeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tipo_Notificacoes_Codigo", unique=true, nullable=false)
    public Integer getTipoNotificacoesCodigo() {
        return this.tipoNotificacoesCodigo;
    }
    
    public void setTipoNotificacoesCodigo(Integer tipoNotificacoesCodigo) {
        this.tipoNotificacoesCodigo = tipoNotificacoesCodigo;
    }

    
    @Column(name="tipo_Notificacoes_Descricao", nullable=false, length=45)
    public String getTipoNotificacoesDescricao() {
        return this.tipoNotificacoesDescricao;
    }
    
    public void setTipoNotificacoesDescricao(String tipoNotificacoesDescricao) {
        this.tipoNotificacoesDescricao = tipoNotificacoesDescricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoNotificacoes")
    public Set getNotificacoeses() {
        return this.notificacoeses;
    }
    
    public void setNotificacoeses(Set notificacoeses) {
        this.notificacoeses = notificacoeses;
    }




}


