package model.bean;
// Generated 23/10/2016 17:38:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPeixes generated by hbm2java
 */
@Entity
@Table(name="tipo_peixes"
    ,catalog="peixepontocom"
)
public class TipoPeixes  implements java.io.Serializable {


     private Integer tipoPeixesCodigo;
     private String tipoPeixesNomePopular;
     private String tipoPeixesNomeCientifico;
     private Set registraLotedepeixes = new HashSet(0);

    public TipoPeixes() {
    }

	
    public TipoPeixes(String tipoPeixesNomePopular) {
        this.tipoPeixesNomePopular = tipoPeixesNomePopular;
    }
    public TipoPeixes(String tipoPeixesNomePopular, String tipoPeixesNomeCientifico, Set registraLotedepeixes) {
       this.tipoPeixesNomePopular = tipoPeixesNomePopular;
       this.tipoPeixesNomeCientifico = tipoPeixesNomeCientifico;
       this.registraLotedepeixes = registraLotedepeixes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tipo_Peixes_Codigo", unique=true, nullable=false)
    public Integer getTipoPeixesCodigo() {
        return this.tipoPeixesCodigo;
    }
    
    public void setTipoPeixesCodigo(Integer tipoPeixesCodigo) {
        this.tipoPeixesCodigo = tipoPeixesCodigo;
    }

    
    @Column(name="tipo_Peixes_NomePopular", nullable=false, length=45)
    public String getTipoPeixesNomePopular() {
        return this.tipoPeixesNomePopular;
    }
    
    public void setTipoPeixesNomePopular(String tipoPeixesNomePopular) {
        this.tipoPeixesNomePopular = tipoPeixesNomePopular;
    }

    
    @Column(name="tipo_Peixes_NomeCientifico", length=45)
    public String getTipoPeixesNomeCientifico() {
        return this.tipoPeixesNomeCientifico;
    }
    
    public void setTipoPeixesNomeCientifico(String tipoPeixesNomeCientifico) {
        this.tipoPeixesNomeCientifico = tipoPeixesNomeCientifico;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoPeixes")
    public Set getRegistraLotedepeixes() {
        return this.registraLotedepeixes;
    }
    
    public void setRegistraLotedepeixes(Set registraLotedepeixes) {
        this.registraLotedepeixes = registraLotedepeixes;
    }




}


