package model.bean;
// Generated 23/10/2016 17:38:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoEstrutura generated by hbm2java
 */
@Entity
@Table(name="tipo_estrutura"
    ,catalog="peixepontocom"
)
public class TipoEstrutura  implements java.io.Serializable {


     private Integer tipoEstruturaCodigo;
     private int tipoEstruturaPrazoDeVidaMeses;
     private String tipoEstruturaDescricao;
     private Set gaiolas = new HashSet(0);

    public TipoEstrutura() {
    }

	
    public TipoEstrutura(int tipoEstruturaPrazoDeVidaMeses, String tipoEstruturaDescricao) {
        this.tipoEstruturaPrazoDeVidaMeses = tipoEstruturaPrazoDeVidaMeses;
        this.tipoEstruturaDescricao = tipoEstruturaDescricao;
    }
    public TipoEstrutura(int tipoEstruturaPrazoDeVidaMeses, String tipoEstruturaDescricao, Set gaiolas) {
       this.tipoEstruturaPrazoDeVidaMeses = tipoEstruturaPrazoDeVidaMeses;
       this.tipoEstruturaDescricao = tipoEstruturaDescricao;
       this.gaiolas = gaiolas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tipo_Estrutura_Codigo", unique=true, nullable=false)
    public Integer getTipoEstruturaCodigo() {
        return this.tipoEstruturaCodigo;
    }
    
    public void setTipoEstruturaCodigo(Integer tipoEstruturaCodigo) {
        this.tipoEstruturaCodigo = tipoEstruturaCodigo;
    }

    
    @Column(name="tipo_Estrutura_PrazoDeVidaMeses", nullable=false)
    public int getTipoEstruturaPrazoDeVidaMeses() {
        return this.tipoEstruturaPrazoDeVidaMeses;
    }
    
    public void setTipoEstruturaPrazoDeVidaMeses(int tipoEstruturaPrazoDeVidaMeses) {
        this.tipoEstruturaPrazoDeVidaMeses = tipoEstruturaPrazoDeVidaMeses;
    }

    
    @Column(name="tipo_Estrutura_Descricao", nullable=false, length=45)
    public String getTipoEstruturaDescricao() {
        return this.tipoEstruturaDescricao;
    }
    
    public void setTipoEstruturaDescricao(String tipoEstruturaDescricao) {
        this.tipoEstruturaDescricao = tipoEstruturaDescricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoEstrutura")
    public Set getGaiolas() {
        return this.gaiolas;
    }
    
    public void setGaiolas(Set gaiolas) {
        this.gaiolas = gaiolas;
    }




}


