package model.bean;
// Generated 23/10/2016 17:38:25 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venda generated by hbm2java
 */
@Entity
@Table(name="venda"
    ,catalog="peixepontocom"
)
public class Venda  implements java.io.Serializable {


     private Integer vendaCodigo;
     private Cliente cliente;
     private RegistraLotedepeixe registraLotedepeixe;
     private BigDecimal vendaValorTotalVenda;
     private Date vendaData;
     private Date vendaHora;
     private BigDecimal vendaPesoTotal;

    public Venda() {
    }

    public Venda(Cliente cliente, RegistraLotedepeixe registraLotedepeixe, BigDecimal vendaValorTotalVenda, Date vendaData, Date vendaHora, BigDecimal vendaPesoTotal) {
       this.cliente = cliente;
       this.registraLotedepeixe = registraLotedepeixe;
       this.vendaValorTotalVenda = vendaValorTotalVenda;
       this.vendaData = vendaData;
       this.vendaHora = vendaHora;
       this.vendaPesoTotal = vendaPesoTotal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="venda_Codigo", unique=true, nullable=false)
    public Integer getVendaCodigo() {
        return this.vendaCodigo;
    }
    
    public void setVendaCodigo(Integer vendaCodigo) {
        this.vendaCodigo = vendaCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_V_Cliente_Codigo", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_V_Registra_LoteDePeixe_Codigo", nullable=false)
    public RegistraLotedepeixe getRegistraLotedepeixe() {
        return this.registraLotedepeixe;
    }
    
    public void setRegistraLotedepeixe(RegistraLotedepeixe registraLotedepeixe) {
        this.registraLotedepeixe = registraLotedepeixe;
    }

    
    @Column(name="venda_ValorTotalVenda", nullable=false, precision=10)
    public BigDecimal getVendaValorTotalVenda() {
        return this.vendaValorTotalVenda;
    }
    
    public void setVendaValorTotalVenda(BigDecimal vendaValorTotalVenda) {
        this.vendaValorTotalVenda = vendaValorTotalVenda;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="venda_Data", nullable=false, length=10)
    public Date getVendaData() {
        return this.vendaData;
    }
    
    public void setVendaData(Date vendaData) {
        this.vendaData = vendaData;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="venda_Hora", nullable=false, length=8)
    public Date getVendaHora() {
        return this.vendaHora;
    }
    
    public void setVendaHora(Date vendaHora) {
        this.vendaHora = vendaHora;
    }

    
    @Column(name="venda_PesoTotal", nullable=false, precision=10)
    public BigDecimal getVendaPesoTotal() {
        return this.vendaPesoTotal;
    }
    
    public void setVendaPesoTotal(BigDecimal vendaPesoTotal) {
        this.vendaPesoTotal = vendaPesoTotal;
    }




}


